/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as certifyRegistrySol from "./CertifyRegistry.sol";
export * as zkpCertifySol from "./ZKPCertify.sol";
export { ZKMockVerifier__factory } from "./ZKMockVerifier__factory";
