/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ZKPCertifyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "certificateCounter"
      | "certificates"
      | "getCertificate"
      | "isMember"
      | "issueCertificate"
      | "issuerNonce"
      | "manageMember"
      | "memberRequests"
      | "members"
      | "requestMembership"
      | "revokeCertificate"
      | "verifiedProofs"
      | "verifier"
      | "verifyGpaProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateIssued"
      | "CertificateRevoked"
      | "MemberDecision"
      | "MemberRequested"
      | "ProofVerified"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "certificateCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [AddressLike, AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerNonce",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manageMember",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "memberRequests",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMembership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyGpaProof",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certificateCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manageMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestMembership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyGpaProof",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    id: BigNumberish,
    issuer: AddressLike,
    holder: AddressLike,
    metadataCid: string,
    metadataCommitment: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    issuer: string,
    holder: string,
    metadataCid: string,
    metadataCommitment: string
  ];
  export interface OutputObject {
    id: bigint;
    issuer: string;
    holder: string;
    metadataCid: string;
    metadataCommitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberDecisionEvent {
  export type InputTuple = [
    issuer: AddressLike,
    holder: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [issuer: string, holder: string, approved: boolean];
  export interface OutputObject {
    issuer: string;
    holder: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRequestedEvent {
  export type InputTuple = [issuer: AddressLike, holder: AddressLike];
  export type OutputTuple = [issuer: string, holder: string];
  export interface OutputObject {
    issuer: string;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [
    certificateId: BigNumberish,
    holder: AddressLike,
    verified: boolean
  ];
  export type OutputTuple = [
    certificateId: bigint,
    holder: string,
    verified: boolean
  ];
  export interface OutputObject {
    certificateId: bigint;
    holder: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZKPCertify extends BaseContract {
  connect(runner?: ContractRunner | null): ZKPCertify;
  waitForDeployment(): Promise<this>;

  interface: ZKPCertifyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  certificateCounter: TypedContractMethod<[], [bigint], "view">;

  certificates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean, bigint] & {
        issuer: string;
        holder: string;
        metadataCid: string;
        metadataCommitment: string;
        issuedAt: bigint;
        revoked: boolean;
        nonce: bigint;
      }
    ],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [certificateId: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        issuer: string;
        holder: string;
        metadataCid: string;
        metadataCommitment: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  isMember: TypedContractMethod<
    [issuer: AddressLike, holder: AddressLike],
    [boolean],
    "view"
  >;

  issueCertificate: TypedContractMethod<
    [
      issuer: AddressLike,
      holder: AddressLike,
      metadataCid: string,
      metadataCommitment: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  issuerNonce: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  manageMember: TypedContractMethod<
    [holder: AddressLike, approve: boolean],
    [void],
    "nonpayable"
  >;

  memberRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, boolean, boolean] & {
        applicant: string;
        approved: boolean;
        decided: boolean;
      }
    ],
    "view"
  >;

  members: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  requestMembership: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCertificate: TypedContractMethod<
    [certificateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifiedProofs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        certificateId: bigint;
        proofHash: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  verifyGpaProof: TypedContractMethod<
    [
      certificateId: BigNumberish,
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish],
      pubSignals: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certificateCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean, bigint] & {
        issuer: string;
        holder: string;
        metadataCid: string;
        metadataCommitment: string;
        issuedAt: bigint;
        revoked: boolean;
        nonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [certificateId: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        issuer: string;
        holder: string;
        metadataCid: string;
        metadataCommitment: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<
    [issuer: AddressLike, holder: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      issuer: AddressLike,
      holder: AddressLike,
      metadataCid: string,
      metadataCommitment: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuerNonce"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "manageMember"
  ): TypedContractMethod<
    [holder: AddressLike, approve: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "memberRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, boolean, boolean] & {
        applicant: string;
        approved: boolean;
        decided: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestMembership"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<[certificateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedProofs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        certificateId: bigint;
        proofHash: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyGpaProof"
  ): TypedContractMethod<
    [
      certificateId: BigNumberish,
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish],
      pubSignals: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "MemberDecision"
  ): TypedContractEvent<
    MemberDecisionEvent.InputTuple,
    MemberDecisionEvent.OutputTuple,
    MemberDecisionEvent.OutputObject
  >;
  getEvent(
    key: "MemberRequested"
  ): TypedContractEvent<
    MemberRequestedEvent.InputTuple,
    MemberRequestedEvent.OutputTuple,
    MemberRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(uint256,address,address,string,bytes32)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRevoked(uint256)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "MemberDecision(address,address,bool)": TypedContractEvent<
      MemberDecisionEvent.InputTuple,
      MemberDecisionEvent.OutputTuple,
      MemberDecisionEvent.OutputObject
    >;
    MemberDecision: TypedContractEvent<
      MemberDecisionEvent.InputTuple,
      MemberDecisionEvent.OutputTuple,
      MemberDecisionEvent.OutputObject
    >;

    "MemberRequested(address,address)": TypedContractEvent<
      MemberRequestedEvent.InputTuple,
      MemberRequestedEvent.OutputTuple,
      MemberRequestedEvent.OutputObject
    >;
    MemberRequested: TypedContractEvent<
      MemberRequestedEvent.InputTuple,
      MemberRequestedEvent.OutputTuple,
      MemberRequestedEvent.OutputObject
    >;

    "ProofVerified(uint256,address,bool)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
  };
}
