/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockGroth16Verifier,
  MockGroth16VerifierInterface,
} from "../../../contracts/mocks/MockGroth16Verifier";

const _abi = [
  {
    inputs: [],
    name: "result",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "value",
        type: "bool",
      },
    ],
    name: "setResult",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff1916600117905534801561001d57600080fd5b5061017c8061002d6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80636537214714610046578063f4b4dc2e14610067578063f5c9d69e1461008a575b600080fd5b6000546100539060ff1681565b604051901515815260200160405180910390f35b6100886100753660046100a6565b6000805460ff1916911515919091179055565b005b6100536100983660046100e6565b60005460ff16949350505050565b6000602082840312156100b857600080fd5b813580151581146100c857600080fd5b9392505050565b80604081018310156100e057600080fd5b92915050565b60008060008061014085870312156100fd57600080fd5b61010786866100cf565b935060c085018681111561011a57600080fd5b60408601935061012a87826100cf565b92505061013b8661010087016100cf565b90509295919450925056fea2646970667358221220d549d99337ca3f4075a23a4f17806f76b6831a6443d9dedbb2f346241996345d64736f6c63430008170033";

type MockGroth16VerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockGroth16VerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockGroth16Verifier__factory extends ContractFactory {
  constructor(...args: MockGroth16VerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockGroth16Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockGroth16Verifier__factory {
    return super.connect(runner) as MockGroth16Verifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockGroth16VerifierInterface {
    return new Interface(_abi) as MockGroth16VerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockGroth16Verifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockGroth16Verifier;
  }
}
