/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockGroth16Verifier,
  MockGroth16VerifierInterface,
} from "../../../contracts/mocks/MockGroth16Verifier";

const _abi = [
  {
    inputs: [],
    name: "result",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "value",
        type: "bool",
      },
    ],
    name: "setResult",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[3]",
        name: "",
        type: "uint256[3]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff1916600117905534801561001d57600080fd5b506101828061002d6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806311479fea146100465780636537214714610076578063f4b4dc2e14610083575b600080fd5b6100626100543660046100bd565b60005460ff16949350505050565b604051901515815260200160405180910390f35b6000546100629060ff1681565b6100a4610091366004610123565b6000805460ff1916911515919091179055565b005b80604081018310156100b757600080fd5b92915050565b6000806000806101608086880312156100d557600080fd5b6100df87876100a6565b945060c08601878111156100f257600080fd5b60408701945061010288826100a6565b93505086818701111561011457600080fd5b50929591945092610100019150565b60006020828403121561013557600080fd5b8135801515811461014557600080fd5b939250505056fea2646970667358221220d4cd9eac225e5f2b3506bb4c79abd3a8807637135091a0cf4723b1b76aea68dd64736f6c63430008170033";

type MockGroth16VerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockGroth16VerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockGroth16Verifier__factory extends ContractFactory {
  constructor(...args: MockGroth16VerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockGroth16Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockGroth16Verifier__factory {
    return super.connect(runner) as MockGroth16Verifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockGroth16VerifierInterface {
    return new Interface(_abi) as MockGroth16VerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockGroth16Verifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockGroth16Verifier;
  }
}
