// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @notice Groth16 verifier interface as generated by snarkjs
 *         (`snarkjs zkey export solidityverifier`) for the range circuit.
 *         The circuit exposes 3 public signals: [root, keyHash, threshold].
 */
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata pubSignals
    ) external view returns (bool);
}

/**
 * @title CertifyRegistry
 * @notice Single on-chain registry for issuers, holders, certificates,
 *         selective disclosures, and zero-knowledge GPA verification.
 * @dev A credential is a set of numeric claims; `metadataCommitment` is the
 *      Merkle root of those claims (see the frontend merkle.ts / range circuit).
 *      `schemaId` names the credential type (diploma, competency, …). Selective
 *      disclosure proves a threshold on one claim without revealing it.
 */
contract CertifyRegistry is AccessControl {
    bytes32 public constant ISSUER_ADMIN_ROLE = keccak256("ISSUER_ADMIN_ROLE");

    enum CertificateStatus {
        Pending,
        Active,
        Revoked
    }

    struct MemberRequest {
        address applicant;
        bool approved;
        bool decided;
    }

    struct Certificate {
        uint256 id;
        address issuer;
        address holder;
        string metadataCid; // IPFS CID for the (encrypted) payload
        bytes32 metadataCommitment; // Merkle root of the credential's claims
        CertificateStatus status;
        uint64 issuedAt;
        bytes32 schemaId; // credential type, e.g. keccak256("diploma.v1")
    }

    struct Disclosure {
        uint256 certificateId;
        address verifier;
        bytes32 queryHash;
        string encryptedPayloadCid;
        uint64 timestamp;
    }

    // Predicate circuits. Each has its own Groth16 verifier (same uint[3] ABI,
    // different verification key). Routed via the registry below.
    bytes32 public constant PREDICATE_RANGE = keccak256("range");
    bytes32 public constant PREDICATE_EQUALITY = keccak256("equality");
    bytes32 public constant PREDICATE_MEMBERSHIP = keccak256("membership");

    mapping(bytes32 predicateId => IGroth16Verifier) public verifiers;
    uint256 private _certificateIdTracker;

    mapping(address issuer => bool) public registeredIssuers;
    mapping(address issuer => mapping(address holder => MemberRequest)) public memberRequests;
    mapping(uint256 certificateId => Certificate) public certificates;
    mapping(address holder => uint256[]) private _holderCertificates;
    mapping(address issuer => uint256[]) private _issuerCertificates;
    mapping(uint256 certificateId => Disclosure[]) private _disclosures;
    // Replay protection: each distinct proof can only be verified once.
    mapping(bytes32 proofHash => bool used) public usedProofs;

    event IssuerRegistered(address indexed issuer, address indexed creator);
    event IssuerRemoved(address indexed issuer, address indexed remover);
    event MemberRequested(address indexed issuer, address indexed holder);
    event MemberDecision(address indexed issuer, address indexed holder, bool approved);
    event CertificateIssued(uint256 indexed certificateId, address indexed issuer, address indexed holder, bytes32 schemaId);
    event CertificateStatusChanged(uint256 indexed certificateId, CertificateStatus status);
    event CertificateShared(uint256 indexed certificateId, address indexed holder, address indexed verifier, bytes32 queryHash, string encryptedPayloadCid);
    event VerifierSet(bytes32 indexed predicateId, address verifier);
    // predicateId names the circuit; keyHash the claim; param = threshold (range) or value (equality).
    event ZKVerified(uint256 indexed certificateId, address indexed verifier, bytes32 indexed predicateId, uint256 keyHash, uint256 param);

    modifier onlyIssuer(address issuer) {
        require(registeredIssuers[issuer], "Issuer not registered");
        require(hasRole(ISSUER_ADMIN_ROLE, issuer), "Caller not issuer");
        _;
    }

    constructor(address admin, address rangeVerifier) {
        require(admin != address(0), "admin required");
        require(rangeVerifier != address(0), "verifier required");
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(ISSUER_ADMIN_ROLE, admin);
        registeredIssuers[admin] = true;
        emit IssuerRegistered(admin, admin);
        verifiers[PREDICATE_RANGE] = IGroth16Verifier(rangeVerifier);
        emit VerifierSet(PREDICATE_RANGE, rangeVerifier);
    }

    /// @notice Register/replace the Groth16 verifier for a predicate circuit.
    function setVerifier(bytes32 predicateId, address verifier) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(verifier != address(0), "invalid verifier");
        verifiers[predicateId] = IGroth16Verifier(verifier);
        emit VerifierSet(predicateId, verifier);
    }

    // ===== Issuer Management =====

    function registerIssuer(address issuer) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(issuer != address(0), "invalid issuer");
        require(!registeredIssuers[issuer], "already issuer");
        registeredIssuers[issuer] = true;
        _grantRole(ISSUER_ADMIN_ROLE, issuer);
        emit IssuerRegistered(issuer, msg.sender);
    }

    function removeIssuer(address issuer) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(registeredIssuers[issuer], "not an issuer");
        registeredIssuers[issuer] = false;
        _revokeRole(ISSUER_ADMIN_ROLE, issuer);
        emit IssuerRemoved(issuer, msg.sender);
    }

    function manageMember(address holder, bool approve) external onlyIssuer(msg.sender) {
        MemberRequest storage request = memberRequests[msg.sender][holder];
        require(request.applicant == holder, "request missing");
        require(!request.decided, "already decided");
        request.decided = true;
        request.approved = approve;
        emit MemberDecision(msg.sender, holder, approve);
    }

    function getIssuerCertificates(address issuer) external view returns (uint256[] memory ids) {
        return _issuerCertificates[issuer];
    }

    // ===== Holder Flows =====

    function requestMembership(address issuer) external {
        require(registeredIssuers[issuer], "issuer unknown");
        MemberRequest storage request = memberRequests[issuer][msg.sender];
        // Allow a fresh request only if none exists, or the previous one was
        // already decided (e.g. rejected and the holder wants to retry).
        require(request.applicant == address(0) || request.decided, "pending request");
        memberRequests[issuer][msg.sender] = MemberRequest({
            applicant: msg.sender,
            approved: false,
            decided: false
        });
        emit MemberRequested(issuer, msg.sender);
    }

    function shareCertificate(
        uint256 certificateId,
        address verifier,
        bytes32 queryHash,
        string calldata encryptedPayloadCid
    ) external {
        Certificate memory cert = certificates[certificateId];
        require(cert.holder == msg.sender, "not holder");
        require(cert.status == CertificateStatus.Active, "inactive cert");
        require(verifier != address(0), "invalid verifier");
        _disclosures[certificateId].push(Disclosure({
            certificateId: certificateId,
            verifier: verifier,
            queryHash: queryHash,
            encryptedPayloadCid: encryptedPayloadCid,
            timestamp: uint64(block.timestamp)
        }));
        emit CertificateShared(certificateId, msg.sender, verifier, queryHash, encryptedPayloadCid);
    }

    function getHolderCertificates(address holder) external view returns (uint256[] memory ids) {
        return _holderCertificates[holder];
    }

    function getDisclosures(uint256 certificateId) external view returns (Disclosure[] memory items) {
        return _disclosures[certificateId];
    }

    // ===== Certificate lifecycle =====

    function issueCertificate(
        address holder,
        string calldata metadataCid,
        bytes32 metadataCommitment,
        bytes32 schemaId
    ) external onlyIssuer(msg.sender) returns (uint256 certificateId) {
        require(holder != address(0), "invalid holder");
        require(bytes(metadataCid).length != 0, "cid required");
        require(metadataCommitment != bytes32(0), "commitment required");
        require(schemaId != bytes32(0), "schema required");
        MemberRequest memory request = memberRequests[msg.sender][holder];
        require(request.approved && request.decided, "holder not approved");
        certificateId = ++_certificateIdTracker;
        certificates[certificateId] = Certificate({
            id: certificateId,
            issuer: msg.sender,
            holder: holder,
            metadataCid: metadataCid,
            metadataCommitment: metadataCommitment,
            status: CertificateStatus.Active,
            issuedAt: uint64(block.timestamp),
            schemaId: schemaId
        });
        _holderCertificates[holder].push(certificateId);
        _issuerCertificates[msg.sender].push(certificateId);
        emit CertificateIssued(certificateId, msg.sender, holder, schemaId);
    }

    function setCertificateStatus(uint256 certificateId, CertificateStatus status) external {
        Certificate storage cert = certificates[certificateId];
        require(cert.issuer != address(0), "unknown cert");
        require(cert.issuer == msg.sender || hasRole(DEFAULT_ADMIN_ROLE, msg.sender), "forbidden");
        cert.status = status;
        emit CertificateStatusChanged(certificateId, status);
    }

    // ===== Verifier =====

    /**
     * @notice Verify a Groth16 RANGE proof: the claim `pubSignals[1]` (keyHash)
     *         has value ≥ `pubSignals[2]` (threshold), without revealing it.
     *         Also used for expiry ("validUntil ≥ now").
     * @param pubSignals [0]=root, [1]=keyHash, [2]=threshold.
     */
    function verifyRangeProof(
        uint256 certificateId,
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata pubSignals
    ) external returns (bool) {
        return _verify(PREDICATE_RANGE, certificateId, a, b, c, pubSignals);
    }

    /**
     * @notice Verify a Groth16 EQUALITY proof: the claim `pubSignals[1]`
     *         (keyHash) equals `pubSignals[2]` (value) in this certificate.
     * @param pubSignals [0]=root, [1]=keyHash, [2]=value.
     */
    function verifyEqualityProof(
        uint256 certificateId,
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata pubSignals
    ) external returns (bool) {
        return _verify(PREDICATE_EQUALITY, certificateId, a, b, c, pubSignals);
    }

    /**
     * @notice Verify a Groth16 SET-MEMBERSHIP proof: the claim `pubSignals[1]`
     *         (keyHash) is one of the values in the set committed by
     *         `pubSignals[2]` (setRoot) — without revealing which one.
     * @param pubSignals [0]=root, [1]=keyHash, [2]=setRoot.
     */
    function verifyMembershipProof(
        uint256 certificateId,
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata pubSignals
    ) external returns (bool) {
        return _verify(PREDICATE_MEMBERSHIP, certificateId, a, b, c, pubSignals);
    }

    function _verify(
        bytes32 predicateId,
        uint256 certificateId,
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata pubSignals
    ) internal returns (bool) {
        IGroth16Verifier verifier = verifiers[predicateId];
        require(address(verifier) != address(0), "unknown predicate");

        Certificate memory cert = certificates[certificateId];
        require(cert.status == CertificateStatus.Active, "inactive cert");

        // The Merkle root proven by the circuit MUST match the certificate's
        // commitment — this binds the anonymous proof to this exact credential.
        require(bytes32(pubSignals[0]) == cert.metadataCommitment, "commitment mismatch");

        // Replay protection: a given proof is single-use.
        bytes32 proofHash = keccak256(abi.encode(predicateId, a, b, c, pubSignals));
        require(!usedProofs[proofHash], "proof already used");

        require(verifier.verifyProof(a, b, c, pubSignals), "invalid proof");

        usedProofs[proofHash] = true;
        emit ZKVerified(certificateId, msg.sender, predicateId, pubSignals[1], pubSignals[2]);
        return true;
    }
}
