// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @notice Groth16 verifier interface as generated by snarkjs
 *         (`snarkjs zkey export solidityverifier`).
 *         The circuit exposes 2 public signals: [commitment, minGpa].
 */
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[2] calldata pubSignals
    ) external view returns (bool);
}

/**
 * @title CertifyRegistry
 * @notice Single on-chain registry for issuers, holders, certificates,
 *         selective disclosures, and zero-knowledge GPA verification.
 * @dev Consolidated contract — the previous parallel `ZKPCertify` has been
 *      removed. `metadataCommitment` is a Poseidon(gpa, secret) commitment
 *      that the ZK circuit reproduces, so on-chain verification is meaningful.
 */
contract CertifyRegistry is AccessControl {
    bytes32 public constant ISSUER_ADMIN_ROLE = keccak256("ISSUER_ADMIN_ROLE");

    enum CertificateStatus {
        Pending,
        Active,
        Revoked
    }

    struct MemberRequest {
        address applicant;
        bool approved;
        bool decided;
    }

    struct Certificate {
        uint256 id;
        address issuer;
        address holder;
        string metadataCid; // IPFS CID for the (encrypted) payload
        bytes32 metadataCommitment; // Poseidon(gpa, secret) — bound by the ZK proof
        CertificateStatus status;
        uint64 issuedAt;
    }

    struct Disclosure {
        uint256 certificateId;
        address verifier;
        bytes32 queryHash;
        string encryptedPayloadCid;
        uint64 timestamp;
    }

    IGroth16Verifier public immutable zkVerifier;
    uint256 private _certificateIdTracker;

    mapping(address issuer => bool) public registeredIssuers;
    mapping(address issuer => mapping(address holder => MemberRequest)) public memberRequests;
    mapping(uint256 certificateId => Certificate) public certificates;
    mapping(address holder => uint256[]) private _holderCertificates;
    mapping(address issuer => uint256[]) private _issuerCertificates;
    mapping(uint256 certificateId => Disclosure[]) private _disclosures;
    // Replay protection: each distinct proof can only be verified once.
    mapping(bytes32 proofHash => bool used) public usedProofs;

    event IssuerRegistered(address indexed issuer, address indexed creator);
    event MemberRequested(address indexed issuer, address indexed holder);
    event MemberDecision(address indexed issuer, address indexed holder, bool approved);
    event CertificateIssued(uint256 indexed certificateId, address indexed issuer, address indexed holder);
    event CertificateStatusChanged(uint256 indexed certificateId, CertificateStatus status);
    event CertificateShared(uint256 indexed certificateId, address indexed holder, address indexed verifier, bytes32 queryHash, string encryptedPayloadCid);
    event ZKVerified(uint256 indexed certificateId, address indexed verifier, uint256 minGpa);

    modifier onlyIssuer(address issuer) {
        require(registeredIssuers[issuer], "Issuer not registered");
        require(hasRole(ISSUER_ADMIN_ROLE, issuer), "Caller not issuer");
        _;
    }

    constructor(address admin, address verifier) {
        require(admin != address(0), "admin required");
        require(verifier != address(0), "verifier required");
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(ISSUER_ADMIN_ROLE, admin);
        registeredIssuers[admin] = true;
        emit IssuerRegistered(admin, admin);
        zkVerifier = IGroth16Verifier(verifier);
    }

    // ===== Issuer Management =====

    function registerIssuer(address issuer) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(issuer != address(0), "invalid issuer");
        require(!registeredIssuers[issuer], "already issuer");
        registeredIssuers[issuer] = true;
        _grantRole(ISSUER_ADMIN_ROLE, issuer);
        emit IssuerRegistered(issuer, msg.sender);
    }

    function manageMember(address holder, bool approve) external onlyIssuer(msg.sender) {
        MemberRequest storage request = memberRequests[msg.sender][holder];
        require(request.applicant == holder, "request missing");
        require(!request.decided, "already decided");
        request.decided = true;
        request.approved = approve;
        emit MemberDecision(msg.sender, holder, approve);
    }

    function getIssuerCertificates(address issuer) external view returns (uint256[] memory ids) {
        return _issuerCertificates[issuer];
    }

    // ===== Holder Flows =====

    function requestMembership(address issuer) external {
        require(registeredIssuers[issuer], "issuer unknown");
        MemberRequest storage request = memberRequests[issuer][msg.sender];
        // Allow a fresh request only if none exists, or the previous one was
        // already decided (e.g. rejected and the holder wants to retry).
        require(request.applicant == address(0) || request.decided, "pending request");
        memberRequests[issuer][msg.sender] = MemberRequest({
            applicant: msg.sender,
            approved: false,
            decided: false
        });
        emit MemberRequested(issuer, msg.sender);
    }

    function shareCertificate(
        uint256 certificateId,
        address verifier,
        bytes32 queryHash,
        string calldata encryptedPayloadCid
    ) external {
        Certificate memory cert = certificates[certificateId];
        require(cert.holder == msg.sender, "not holder");
        require(cert.status == CertificateStatus.Active, "inactive cert");
        require(verifier != address(0), "invalid verifier");
        _disclosures[certificateId].push(Disclosure({
            certificateId: certificateId,
            verifier: verifier,
            queryHash: queryHash,
            encryptedPayloadCid: encryptedPayloadCid,
            timestamp: uint64(block.timestamp)
        }));
        emit CertificateShared(certificateId, msg.sender, verifier, queryHash, encryptedPayloadCid);
    }

    function getHolderCertificates(address holder) external view returns (uint256[] memory ids) {
        return _holderCertificates[holder];
    }

    function getDisclosures(uint256 certificateId) external view returns (Disclosure[] memory items) {
        return _disclosures[certificateId];
    }

    // ===== Certificate lifecycle =====

    function issueCertificate(
        address holder,
        string calldata metadataCid,
        bytes32 metadataCommitment
    ) external onlyIssuer(msg.sender) returns (uint256 certificateId) {
        require(holder != address(0), "invalid holder");
        require(bytes(metadataCid).length != 0, "cid required");
        require(metadataCommitment != bytes32(0), "commitment required");
        MemberRequest memory request = memberRequests[msg.sender][holder];
        require(request.approved && request.decided, "holder not approved");
        certificateId = ++_certificateIdTracker;
        certificates[certificateId] = Certificate({
            id: certificateId,
            issuer: msg.sender,
            holder: holder,
            metadataCid: metadataCid,
            metadataCommitment: metadataCommitment,
            status: CertificateStatus.Active,
            issuedAt: uint64(block.timestamp)
        });
        _holderCertificates[holder].push(certificateId);
        _issuerCertificates[msg.sender].push(certificateId);
        emit CertificateIssued(certificateId, msg.sender, holder);
    }

    function setCertificateStatus(uint256 certificateId, CertificateStatus status) external {
        Certificate storage cert = certificates[certificateId];
        require(cert.issuer != address(0), "unknown cert");
        require(cert.issuer == msg.sender || hasRole(DEFAULT_ADMIN_ROLE, msg.sender), "forbidden");
        cert.status = status;
        emit CertificateStatusChanged(certificateId, status);
    }

    // ===== Verifier =====

    /**
     * @notice Verify a Groth16 selective-disclosure proof that the holder's
     *         GPA meets `pubSignals[1]` (minGpa), without revealing the GPA.
     * @param certificateId Certificate whose commitment the proof must open.
     * @param a,b,c Groth16 proof points.
     * @param pubSignals [0]=commitment, [1]=minGpa (both circuit public signals).
     */
    function verifySelectiveProof(
        uint256 certificateId,
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[2] calldata pubSignals
    ) external returns (bool) {
        Certificate memory cert = certificates[certificateId];
        require(cert.status == CertificateStatus.Active, "inactive cert");

        // The commitment proven by the circuit MUST match the one issued
        // on-chain — this binds the anonymous proof to this exact certificate.
        require(bytes32(pubSignals[0]) == cert.metadataCommitment, "commitment mismatch");

        // Replay protection: a given proof is single-use.
        bytes32 proofHash = keccak256(abi.encode(a, b, c, pubSignals));
        require(!usedProofs[proofHash], "proof already used");

        require(zkVerifier.verifyProof(a, b, c, pubSignals), "invalid proof");

        usedProofs[proofHash] = true;
        emit ZKVerified(certificateId, msg.sender, pubSignals[1]);
        return true;
    }
}
