// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// Interface for Groth16 Verifier (generated by snarkjs)
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[2] calldata _pubSignals
    ) external view returns (bool);
}

contract ZKPCertify {
    // Existing structs and mappings
    struct Certificate {
        address issuer;
        address holder;
        string metadataCid;
        bytes32 metadataCommitment;
        uint256 issuedAt;
        bool revoked;
    }

    struct MemberRequest {
        address applicant;
        bool approved;
        bool decided;
    }

    mapping(uint256 => Certificate) public certificates;
    mapping(address => mapping(address => MemberRequest)) public memberRequests;
    mapping(address => mapping(address => bool)) public members;
    
    uint256 public certificateCounter;
    
    // ZKP Verifier contract address
    IVerifier public verifier;

    // Events
    event CertificateIssued(
        uint256 indexed id,
        address indexed issuer,
        address indexed holder,
        string metadataCid,
        bytes32 metadataCommitment
    );
    
    event CertificateRevoked(uint256 indexed id);
    
    event ProofVerified(
        uint256 indexed certificateId,
        address indexed holder,
        bool verified
    );

    event MemberRequested(address indexed issuer, address indexed holder);
    event MemberDecision(address indexed issuer, address indexed holder, bool approved);

    modifier onlyIssuer(address issuer) {
        require(msg.sender == issuer, "not issuer");
        _;
    }

    modifier onlyHolder(uint256 certificateId) {
        require(certificates[certificateId].holder == msg.sender, "not holder");
        _;
    }

    constructor(address _verifier) {
        verifier = IVerifier(_verifier);
    }

    // Existing functions
    function requestMembership(address issuer) external {
        require(!members[issuer][msg.sender], "already member");
        MemberRequest storage request = memberRequests[issuer][msg.sender];
        require(request.applicant == address(0), "request exists");
        
        request.applicant = msg.sender;
        emit MemberRequested(issuer, msg.sender);
    }

    function manageMember(address holder, bool approve) external onlyIssuer(msg.sender) {
        MemberRequest storage request = memberRequests[msg.sender][holder];
        require(request.applicant == holder, "request missing");
        require(!request.decided, "already decided");
        
        request.decided = true;
        request.approved = approve;
        
        if (approve) {
            members[msg.sender][holder] = true;
        }
        
        emit MemberDecision(msg.sender, holder, approve);
    }

    function issueCertificate(
        address holder,
        string memory metadataCid,
        bytes32 metadataCommitment
    ) external {
        require(members[msg.sender][holder], "holder not member");
        
        certificateCounter++;
        certificates[certificateCounter] = Certificate({
            issuer: msg.sender,
            holder: holder,
            metadataCid: metadataCid,
            metadataCommitment: metadataCommitment,
            issuedAt: block.timestamp,
            revoked: false
        });

        emit CertificateIssued(
            certificateCounter,
            msg.sender,
            holder,
            metadataCid,
            metadataCommitment
        );
    }

    function revokeCertificate(uint256 certificateId) external {
        Certificate storage cert = certificates[certificateId];
        require(cert.issuer == msg.sender, "not issuer");
        require(!cert.revoked, "already revoked");
        
        cert.revoked = true;
        emit CertificateRevoked(certificateId);
    }

    // NEW: ZKP Verification Functions
    
        /**
     * @notice Verify a zero-knowledge proof for certificate GPA
     * @param certificateId The ID of the certificate
     * @param pA Proof component A (G1)
     * @param pB Proof component B (G2)
     * @param pC Proof component C (G1)
     * @param pubSignals Public signals [metadataCommitment, minGpa]
     * @return bool Whether the proof is valid
     */
    function verifyGpaProof(
        uint256 certificateId,
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC,
        uint[2] calldata pubSignals
    ) external returns (bool) {
        Certificate storage cert = certificates[certificateId];
        require(!cert.revoked, "certificate revoked");
        
        // Verify that the first public signal matches the certificate's metadata commitment
        require(
            bytes32(pubSignals[0]) == cert.metadataCommitment,
            "metadata commitment mismatch"
        );

        // Verify the ZK proof using the verifier contract
        bool verified = verifier.verifyProof(pA, pB, pC, pubSignals);
        
        emit ProofVerified(certificateId, msg.sender, verified);
        
        return verified;
    }

    /**
     * @notice Get certificate details (public view)
     */
    function getCertificate(uint256 certificateId) 
        external 
        view 
        returns (
            address issuer,
            address holder,
            string memory metadataCid,
            bytes32 metadataCommitment,
            uint256 issuedAt,
            bool revoked
        ) 
    {
        Certificate storage cert = certificates[certificateId];
        return (
            cert.issuer,
            cert.holder,
            cert.metadataCid,
            cert.metadataCommitment,
            cert.issuedAt,
            cert.revoked
        );
    }

    /**
     * @notice Check if holder is a member of issuer
     */
    function isMember(address issuer, address holder) external view returns (bool) {
        return members[issuer][holder];
    }
}