/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as certifyRegistrySol from "./CertifyRegistry.sol";
export type { certifyRegistrySol };
export type { ZKMockVerifier } from "./ZKMockVerifier";
