/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as certifyRegistrySol from "./CertifyRegistry.sol";
export type { certifyRegistrySol };
import type * as zkpCertifySol from "./ZKPCertify.sol";
export type { zkpCertifySol };
import type * as verifierSol from "./verifier.sol";
export type { verifierSol };
