// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.7.0 <0.9.0;

/**
 * ⚠️  PLACEHOLDER — regenerated by `cd zk && ./build.sh`.
 * The real verifier for membership.circom is snarkjs output, renamed to
 * `MembershipVerifier` by the build. Until then `verifyProof` returns false.
 * pubSignals = [root, keyHash, setRoot].
 */
contract MembershipVerifier {
    function verifyProof(
        uint[2] calldata,
        uint[2][2] calldata,
        uint[2] calldata,
        uint[3] calldata
    ) public pure returns (bool) {
        return false;
    }
}
