/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CertifyRegistry {
  export type DisclosureStruct = {
    certificateId: BigNumberish;
    verifier: AddressLike;
    queryHash: BytesLike;
    encryptedPayloadCid: string;
    timestamp: BigNumberish;
  };

  export type DisclosureStructOutput = [
    certificateId: bigint,
    verifier: string,
    queryHash: string,
    encryptedPayloadCid: string,
    timestamp: bigint
  ] & {
    certificateId: bigint;
    verifier: string;
    queryHash: string;
    encryptedPayloadCid: string;
    timestamp: bigint;
  };
}

export interface CertifyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ISSUER_ADMIN_ROLE"
      | "certificates"
      | "getDisclosures"
      | "getHolderCertificates"
      | "getIssuerCertificates"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "issueCertificate"
      | "manageMember"
      | "memberRequests"
      | "registerIssuer"
      | "registeredIssuers"
      | "renounceRole"
      | "requestMembership"
      | "revokeRole"
      | "setCertificateStatus"
      | "shareCertificate"
      | "supportsInterface"
      | "verifySelectiveProof"
      | "zkVerifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateIssued"
      | "CertificateShared"
      | "CertificateStatusChanged"
      | "IssuerRegistered"
      | "MemberDecision"
      | "MemberRequested"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ZKVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisclosures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHolderCertificates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuerCertificates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manageMember",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "memberRequests",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMembership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCertificateStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shareCertificate",
    values: [BigNumberish, AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySelectiveProof",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "zkVerifier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisclosures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHolderCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIssuerCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manageMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMembership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCertificateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySelectiveProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zkVerifier", data: BytesLike): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    certificateId: BigNumberish,
    issuer: AddressLike,
    holder: AddressLike
  ];
  export type OutputTuple = [
    certificateId: bigint,
    issuer: string,
    holder: string
  ];
  export interface OutputObject {
    certificateId: bigint;
    issuer: string;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateSharedEvent {
  export type InputTuple = [
    certificateId: BigNumberish,
    holder: AddressLike,
    verifier: AddressLike,
    queryHash: BytesLike,
    encryptedPayloadCid: string
  ];
  export type OutputTuple = [
    certificateId: bigint,
    holder: string,
    verifier: string,
    queryHash: string,
    encryptedPayloadCid: string
  ];
  export interface OutputObject {
    certificateId: bigint;
    holder: string;
    verifier: string;
    queryHash: string;
    encryptedPayloadCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateStatusChangedEvent {
  export type InputTuple = [certificateId: BigNumberish, status: BigNumberish];
  export type OutputTuple = [certificateId: bigint, status: bigint];
  export interface OutputObject {
    certificateId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRegisteredEvent {
  export type InputTuple = [issuer: AddressLike, creator: AddressLike];
  export type OutputTuple = [issuer: string, creator: string];
  export interface OutputObject {
    issuer: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberDecisionEvent {
  export type InputTuple = [
    issuer: AddressLike,
    holder: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [issuer: string, holder: string, approved: boolean];
  export interface OutputObject {
    issuer: string;
    holder: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRequestedEvent {
  export type InputTuple = [issuer: AddressLike, holder: AddressLike];
  export type OutputTuple = [issuer: string, holder: string];
  export interface OutputObject {
    issuer: string;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZKVerifiedEvent {
  export type InputTuple = [
    certificateId: BigNumberish,
    verifier: AddressLike,
    queryHash: BytesLike
  ];
  export type OutputTuple = [
    certificateId: bigint,
    verifier: string,
    queryHash: string
  ];
  export interface OutputObject {
    certificateId: bigint;
    verifier: string;
    queryHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertifyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertifyRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertifyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  certificates: TypedContractMethod<
    [certificateId: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, bigint] & {
        id: bigint;
        issuer: string;
        holder: string;
        metadataCid: string;
        metadataCommitment: string;
        status: bigint;
        issuedAt: bigint;
      }
    ],
    "view"
  >;

  getDisclosures: TypedContractMethod<
    [certificateId: BigNumberish],
    [CertifyRegistry.DisclosureStructOutput[]],
    "view"
  >;

  getHolderCertificates: TypedContractMethod<
    [holder: AddressLike],
    [bigint[]],
    "view"
  >;

  getIssuerCertificates: TypedContractMethod<
    [issuer: AddressLike],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  issueCertificate: TypedContractMethod<
    [holder: AddressLike, metadataCid: string, metadataCommitment: BytesLike],
    [bigint],
    "nonpayable"
  >;

  manageMember: TypedContractMethod<
    [holder: AddressLike, approve: boolean],
    [void],
    "nonpayable"
  >;

  memberRequests: TypedContractMethod<
    [issuer: AddressLike, holder: AddressLike],
    [
      [string, boolean, boolean] & {
        applicant: string;
        approved: boolean;
        decided: boolean;
      }
    ],
    "view"
  >;

  registerIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  registeredIssuers: TypedContractMethod<
    [issuer: AddressLike],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestMembership: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setCertificateStatus: TypedContractMethod<
    [certificateId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  shareCertificate: TypedContractMethod<
    [
      certificateId: BigNumberish,
      verifier: AddressLike,
      queryHash: BytesLike,
      encryptedPayloadCid: string
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verifySelectiveProof: TypedContractMethod<
    [certificateId: BigNumberish, proof: BytesLike, queryHash: BytesLike],
    [boolean],
    "nonpayable"
  >;

  zkVerifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [certificateId: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, bigint] & {
        id: bigint;
        issuer: string;
        holder: string;
        metadataCid: string;
        metadataCommitment: string;
        status: bigint;
        issuedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDisclosures"
  ): TypedContractMethod<
    [certificateId: BigNumberish],
    [CertifyRegistry.DisclosureStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHolderCertificates"
  ): TypedContractMethod<[holder: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getIssuerCertificates"
  ): TypedContractMethod<[issuer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [holder: AddressLike, metadataCid: string, metadataCommitment: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "manageMember"
  ): TypedContractMethod<
    [holder: AddressLike, approve: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "memberRequests"
  ): TypedContractMethod<
    [issuer: AddressLike, holder: AddressLike],
    [
      [string, boolean, boolean] & {
        applicant: string;
        approved: boolean;
        decided: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredIssuers"
  ): TypedContractMethod<[issuer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestMembership"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCertificateStatus"
  ): TypedContractMethod<
    [certificateId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shareCertificate"
  ): TypedContractMethod<
    [
      certificateId: BigNumberish,
      verifier: AddressLike,
      queryHash: BytesLike,
      encryptedPayloadCid: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifySelectiveProof"
  ): TypedContractMethod<
    [certificateId: BigNumberish, proof: BytesLike, queryHash: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "zkVerifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateShared"
  ): TypedContractEvent<
    CertificateSharedEvent.InputTuple,
    CertificateSharedEvent.OutputTuple,
    CertificateSharedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateStatusChanged"
  ): TypedContractEvent<
    CertificateStatusChangedEvent.InputTuple,
    CertificateStatusChangedEvent.OutputTuple,
    CertificateStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRegistered"
  ): TypedContractEvent<
    IssuerRegisteredEvent.InputTuple,
    IssuerRegisteredEvent.OutputTuple,
    IssuerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MemberDecision"
  ): TypedContractEvent<
    MemberDecisionEvent.InputTuple,
    MemberDecisionEvent.OutputTuple,
    MemberDecisionEvent.OutputObject
  >;
  getEvent(
    key: "MemberRequested"
  ): TypedContractEvent<
    MemberRequestedEvent.InputTuple,
    MemberRequestedEvent.OutputTuple,
    MemberRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ZKVerified"
  ): TypedContractEvent<
    ZKVerifiedEvent.InputTuple,
    ZKVerifiedEvent.OutputTuple,
    ZKVerifiedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(uint256,address,address)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateShared(uint256,address,address,bytes32,string)": TypedContractEvent<
      CertificateSharedEvent.InputTuple,
      CertificateSharedEvent.OutputTuple,
      CertificateSharedEvent.OutputObject
    >;
    CertificateShared: TypedContractEvent<
      CertificateSharedEvent.InputTuple,
      CertificateSharedEvent.OutputTuple,
      CertificateSharedEvent.OutputObject
    >;

    "CertificateStatusChanged(uint256,uint8)": TypedContractEvent<
      CertificateStatusChangedEvent.InputTuple,
      CertificateStatusChangedEvent.OutputTuple,
      CertificateStatusChangedEvent.OutputObject
    >;
    CertificateStatusChanged: TypedContractEvent<
      CertificateStatusChangedEvent.InputTuple,
      CertificateStatusChangedEvent.OutputTuple,
      CertificateStatusChangedEvent.OutputObject
    >;

    "IssuerRegistered(address,address)": TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;
    IssuerRegistered: TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;

    "MemberDecision(address,address,bool)": TypedContractEvent<
      MemberDecisionEvent.InputTuple,
      MemberDecisionEvent.OutputTuple,
      MemberDecisionEvent.OutputObject
    >;
    MemberDecision: TypedContractEvent<
      MemberDecisionEvent.InputTuple,
      MemberDecisionEvent.OutputTuple,
      MemberDecisionEvent.OutputObject
    >;

    "MemberRequested(address,address)": TypedContractEvent<
      MemberRequestedEvent.InputTuple,
      MemberRequestedEvent.OutputTuple,
      MemberRequestedEvent.OutputObject
    >;
    MemberRequested: TypedContractEvent<
      MemberRequestedEvent.InputTuple,
      MemberRequestedEvent.OutputTuple,
      MemberRequestedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ZKVerified(uint256,address,bytes32)": TypedContractEvent<
      ZKVerifiedEvent.InputTuple,
      ZKVerifiedEvent.OutputTuple,
      ZKVerifiedEvent.OutputObject
    >;
    ZKVerified: TypedContractEvent<
      ZKVerifiedEvent.InputTuple,
      ZKVerifiedEvent.OutputTuple,
      ZKVerifiedEvent.OutputObject
    >;
  };
}
